### ISSUE TITLE
tanh and its derivative are both wrong

### ISSUE THREAD

**Issue by felipetavares** [carlosribeiro1987/NeuralNetworksStudies#1]
This is what you did (red *should* be tanh, blue should be its derivative):

![image](https://user-images.githubusercontent.com/2183824/64975029-7911c080-d884-11e9-98f9-22a6b661c2d3.png)

This is what it should be (green is tanh, purple is its derivative):

![image](https://user-images.githubusercontent.com/2183824/64975104-9c3c7000-d884-11e9-9e39-fa9298811891.png)

The wrong part is this:

```cs
(BoundNumbers.Exp(input * 2.0) - 1) / (BoundNumbers.Exp(input * 2.0 + 1))
```

It should be

```cs
(BoundNumbers.Exp(input) - BoundNumbers.Exp(-input)) / (BoundNumbers.Exp(input) + BoundNumbers.Exp(-input))
```

The derivative calculation is right, but since it uses a wrong definition of tanh it produces a wrong result too (which isn't even the derivative of the described function, this will cause errors in any gradient-based method since they rely on correct derivatives to learn).

**Comment by carlosribeiro1987** [comment]
Thanks man. I'll correct this.

**Comment by carlosribeiro1987** [comment]
Thanks man. I'll fix these issues.

**Comment by carlosribeiro1987** [comment]
The suggested changes were made on the code. I'm closing this issue.
