### ISSUE TITLE
sigmoid derivative is wrong

### ISSUE THREAD

**Issue by felipetavares** [carlosribeiro1987/NeuralNetworksStudies#2]
In the below graph, the black curve is the sigmoid function. In red is your calculation for the derivative. In blue is the correct one.

![image](https://user-images.githubusercontent.com/2183824/64976710-5e414b00-d888-11e9-9478-a3a3c8c3fa82.png)

**Comment by carlosribeiro1987** [comment]
My intent when I created this code was to pass the result of `ActivationFunction()` as input parameter on `DerivativeFunction()`, then it should work as if its code was
```cs 
public double DerivativeFunction(double d) {
    return ActivationFunction(d) * (1.0 - ActivationFunction(d));
} 
```
